name: Setup 'Terraform'
description: 'Setup Terraform'
inputs:
  aqua_version:
    description: 'The version of Aqua to use'
    required: true
  project_id:
    description: 'The project ID to use'
    required: true
  workload_identity_provider:
    description: 'The workload identity provider to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: auth-google
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ inputs.project_id }}

    # Cache Aqua tools
    - name: Cache Tools
      id: cache-tools
      uses: actions/cache@v4
      with:
        path: ~/.local/share/aquaproj-aqua
        key: cache-tools-${{ hashFiles('aqua.yaml') }}

    # aqua.yamlから取得したパッケージをインストール
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@v3.1.2
      with:
        aqua_version: ${{ inputs.aqua_version }}
        aqua_opts: "" # Lazy install（aqua i -l） がデフォルトで有効になっているため、aqua_optsに空文字を指定して'-l'オプションを取り除く

    - name: Terraform fmt
      id: fmt
      shell: bash
      run: terraform fmt -recursive -check -diff
      continue-on-error: true

    - name: Terraform Init
      id: init
      shell: bash
      run: terraform init
      working-directory: ./terraform/projects/${{ inputs.project_id }}

    - name: Terraform Validate
      id: validate
      shell: bash
      run: terraform validate -no-color
