name: terraform-docs
run-name: terraform docs generation

on:
  pull_request:
    paths:
      - "terraform/**.tf"

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.project }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            project:
              - terraform/**.tf

  terraform-docs:
    needs: filter
    if: ${{ needs.filter.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Terraform docs
        id: docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ./terraform/
          output-file: README.md
          output-method: inject
          git-push: "true"
